/**
 * Seed v3: Apply Current Account — apply-ca-1 to apply-ca-6
 *
 * Screens (7 total):
 *   1. mobile_number_form   — Mobile number entry + consent
 *   2. email_form           — Email + social login
 *   3. ektp_instructions    — e-KTP photo guide
 *   4. ektp_capture         — Camera capture
 *   5. ektp_review          — e-KTP details review with address cascading
 *   6. employment_form      — Employment details with conditional visibility
 *   7. confirmation         — Full review + slide to confirm
 *
 * Binding approach (new):
 *   - `name` on the component is the state key (replaces binding.path)
 *   - `scope` on the component is the state scope (replaces binding.scope)
 *   - `defaultValue` is a plain field on the component (no wrapper)
 *   - No `binding` component needed
 *
 * Usage:
 *   SEED_DATA=apply-ca-v3 npm run develop
 */

import type { Core } from "@strapi/strapi";

type StrapiInstance = Core.Strapi;

async function findScreen(strapi: StrapiInstance, screenId: string) {
  const results = await strapi.documents("api::screen.screen").findMany({
    filters: { screenId: { $eq: screenId } },
    status: "draft",
    limit: 1,
  });
  return results[0] ?? null;
}

async function createAndPublishScreen(strapi: StrapiInstance, data: Record<string, unknown>) {
  const screenId = data.screenId as string;
  const existing = await findScreen(strapi, screenId);

  if (existing) {
    console.log(`[seed-v3] Screen already exists — skipping: ${screenId}`);
    return existing;
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const created = await strapi.documents("api::screen.screen").create({ data: data as any });
  await strapi.documents("api::screen.screen").publish({ documentId: created.documentId });

  console.log(`[seed-v3] ✓ Screen created & published: ${screenId}`);
  return created;
}

// ---------------------------------------------------------------------------
// Shared header helpers
// ---------------------------------------------------------------------------

function progressHeader(step: number, maxStep = 7) {
  return {
    __component: "ui.progress-bar",
    testId: "progress_bar",
    componentId: "progress_bar",
    name: "progressBar",
    currentStep: step,
    maxStep,
    enabled: true,
    span: 12,
  };
}

function productNameText() {
  return {
    __component: "ui.text",
    testId: "product_name",
    componentId: "product_name",
    label: "",
    name: "productName",
    scope: "journeyState",
    variant: "subtitle",
    enabled: true,
    valueSource: { type: "journeyState", path: "product.name" },
    span: 12,
  };
}

function screenTitleText(label: string) {
  return {
    __component: "ui.text",
    testId: "screen_title",
    componentId: "screen_title",
    label,
    name: "screenTitle",
    variant: "title",
    enabled: true,
    span: 12,
  };
}

function screenSubtitleText(id: string, label: string) {
  return {
    __component: "ui.text",
    testId: id,
    componentId: id,
    label,
    name: id,
    variant: "subtitle",
    enabled: true,
    span: 12,
  };
}

function nextButton() {
  return {
    __component: "ui.button",
    testId: "next_button",
    componentId: "next_button",
    label: "Next",
    name: "nextButton",
    variant: "primary",
    enabled: true,
    action: { type: "NEXT_SCREEN" },
    span: 12,
  };
}

// ---------------------------------------------------------------------------
// Screen definitions
// ---------------------------------------------------------------------------

const screens = [
  // // ── 1. Mobile Number ─────────────────────────────────────────────────────
  // {
  //   screenId: "mobile_number_form",
  //   screenKey: "MOBILE_NUMBER_FORM",
  //   version: 1,
  //   meta: { label: "Apply", enableBackButton: false, enableCloseButton: true },
  //   header: [progressHeader(1), productNameText(), screenTitleText("Enter your mobile number")],
  //   body: [
  //     {
  //       __component: "ui.text-input",
  //       testId: "mobile_number",
  //       componentId: "mobile_number",
  //       label: "Mobile number",
  //       name: "mobileNumber",
  //       scope: "journeyState",
  //       placeholder: "Enter mobile number",
  //       prefix: "+62",
  //       inputMode: "numeric",
  //       defaultValue: "",
  //       maxLength: 13,
  //       required: true,
  //       enabled: true,
  //       editable: true,
  //       validations: [
  //         { rule: "required", message: "Mobile number is required" },
  //         { rule: "pattern", value: "^[0-9]{8,13}$", message: "Enter a valid Indonesian mobile number" },
  //       ],
  //       dynamic: {
  //         enabled: true,
  //         type: "VALUE",
  //         target: "defaultValue",
  //         source: { type: "FACT", path: "existingMobileNumber" },
  //       },
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.text",
  //       testId: "disclaimer_label",
  //       componentId: "disclaimer_label",
  //       label: "Disclaimer:",
  //       name: "disclaimerLabel",
  //       variant: "label",
  //       enabled: true,
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.text",
  //       testId: "disclaimer_text",
  //       componentId: "disclaimer_text",
  //       label:
  //         "Maybank collects your mobile number for purposes including, but not limited to, security feature activation, ATM card activation, sending SMS TAC codes and Mobile App registration. SMS TACs will be sent to your registered mobile number. Your information will be stored securely in Maybank\u2019s system, which protects the confidentiality of customer data.",
  //       name: "disclaimerText",
  //       variant: "body",
  //       enabled: true,
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.checkbox",
  //       testId: "mobile_consent",
  //       componentId: "mobile_consent",
  //       title: "I hereby declare:",
  //       label:
  //         "I have read and understood the above use of my mobile number. I agree to provide my mobile number and consent to it being used for these purposes.",
  //       name: "mobileConsent",
  //       scope: "journeyState",
  //       defaultValue: false,
  //       required: true,
  //       enabled: true,
  //       editable: true,
  //       validations: [{ rule: "required", message: "You must agree to continue" }],
  //       span: 12,
  //     },
  //   ],
  //   footer: [nextButton()],
  // },

  // // ── 2. Email ──────────────────────────────────────────────────────────────
  // {
  //   screenId: "email_form",
  //   screenKey: "EMAIL_FORM",
  //   version: 1,
  //   meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
  //   header: [
  //     progressHeader(2),
  //     productNameText(),
  //     screenTitleText("Your email address"),
  //     screenSubtitleText("screen_subtitle", "Fill in your email address"),
  //   ],
  //   body: [
  //     {
  //       __component: "ui.text-input",
  //       testId: "email_address",
  //       componentId: "email_address",
  //       label: "Email address",
  //       name: "emailAddress",
  //       scope: "journeyState",
  //       placeholder: "Enter email address",
  //       inputMode: "email",
  //       defaultValue: "",
  //       maxLength: 200,
  //       required: true,
  //       enabled: true,
  //       editable: true,
  //       validations: [
  //         { rule: "required", message: "Email address is required" },
  //         { rule: "pattern", value: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$", message: "Enter a valid email address" },
  //       ],
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.text-input",
  //       testId: "confirm_email_address",
  //       componentId: "confirm_email_address",
  //       label: "Confirm email address",
  //       name: "confirmEmailAddress",
  //       scope: "journeyState",
  //       placeholder: "Re-enter email address",
  //       inputMode: "email",
  //       defaultValue: "",
  //       maxLength: 200,
  //       required: true,
  //       enabled: true,
  //       editable: true,
  //       validations: [
  //         { rule: "required", message: "Confirm email address is required" },
  //         { rule: "match", value: "emailAddress", message: "Email addresses do not match" },
  //       ],
  //       span: 12,
  //     },
  //   ],
  //   footer: [
  //     nextButton(),
  //     {
  //       __component: "ui.divider",
  //       testId: "footer_divider",
  //       componentId: "footer_divider",
  //       label: "Or continue with an account",
  //       name: "footerDivider",
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.button",
  //       testId: "google_account_button",
  //       componentId: "google_account_button",
  //       label: "Continue with Google",
  //       name: "googleAccountButton",
  //       variant: "secondary",
  //       enabled: true,
  //       icon: { name: "googleLogo", position: "left" },
  //       action: { type: "SOCIAL_LOGIN", provider: "GOOGLE" },
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.button",
  //       testId: "apple_account_button",
  //       componentId: "apple_account_button",
  //       label: "Continue with Apple",
  //       name: "appleAccountButton",
  //       variant: "secondary",
  //       enabled: true,
  //       icon: { name: "appleLogo", position: "left" },
  //       action: { type: "SOCIAL_LOGIN", provider: "APPLE" },
  //       span: 12,
  //     },
  //   ],
  // },

  // // ── 3. e-KTP Photo Instructions ──────────────────────────────────────────
  // {
  //   screenId: "ektp_instructions",
  //   screenKey: "EKTP_INSTRUCTIONS",
  //   version: 1,
  //   meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
  //   header: [progressHeader(3), productNameText(), screenTitleText("E-KTP photo instructions")],
  //   body: [
  //     {
  //       __component: "ui.item-list",
  //       testId: "ektp_hints",
  //       componentId: "ektpHints",
  //       label: "Tips for a good photo",
  //       name: "ektpHints",
  //       enabled: true,
  //       options: [
  //         {
  //           value: "hint_original",
  //           label: "Take a photo of your original e-KTP, not a copy or photocopy.",
  //           // media: set icon via CMS admin
  //         },
  //         {
  //           value: "hint_frame",
  //           label: "Position your e-KTP so the entire card fits the frame clearly.",
  //           // media: set icon via CMS admin
  //         },
  //         {
  //           value: "hint_readable",
  //           label: "Ensure all details on the e-KTP are clearly readable.",
  //           // media: set icon via CMS admin
  //         },
  //       ],
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.image-preview",
  //       testId: "ektp_example",
  //       componentId: "ektp_example",
  //       label: "Example of e-KTP",
  //       name: "ektpExample",
  //       enabled: true,
  //       editable: false,
  //       span: 12,
  //     },
  //   ],
  //   footer: [
  //     {
  //       __component: "ui.button",
  //       testId: "start_button",
  //       componentId: "start_button",
  //       label: "Get started",
  //       name: "startButton",
  //       variant: "primary",
  //       enabled: true,
  //       action: { type: "NEXT_SCREEN" },
  //       span: 12,
  //     },
  //   ],
  // },

  // // ── 4. e-KTP Camera Capture ───────────────────────────────────────────────
  // {
  //   screenId: "ektp_capture",
  //   screenKey: "EKTP_CAPTURE",
  //   version: 1,
  //   meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
  //   body: [
  //     {
  //       __component: "ui.camera-capture",
  //       testId: "ektp_camera",
  //       componentId: "ektp_camera",
  //       name: "ektpImage",
  //       scope: "journeyState",
  //       overlayShape: "rectangle",
  //       overlayAspect: "1.586",
  //       overlayHint: "Please ensure your e-KTP details are visible in the frame",
  //       onComplete: {
  //         action: {
  //           key: "ektpCaptured",
  //           type: "api_call",
  //           payload: { serviceCode: "OCR_EKTP", actionId: "ektp-captured" },
  //         },
  //       },
  //       span: 12,
  //     },
  //   ],
  //   footer: [],
  // },

  // ── 5. e-KTP Review ───────────────────────────────────────────────────────
  {
    screenId: "ektp_review",
    screenKey: "EKTP_REVIEW",
    version: 1,
    meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
    header: [
      progressHeader(3),
      productNameText(),
      screenTitleText("Your e-KTP details"),
      {
        __component: "ui.image-preview",
        testId: "ektp_preview",
        componentId: "ektp_preview",
        name: "ektpImage",
        scope: "journeyState",
        enabled: true,
        editable: false,
        valueSource: { type: "journeyState", path: "ektpImage" },
        span: 12,
      },
    ],
    body: [
      {
        __component: "ui.text-input",
        testId: "ektp_number",
        componentId: "ektp_number",
        label: "e-KTP number",
        name: "ektpNumber",
        scope: "journeyState",
        placeholder: "16-digit KTP number",
        inputMode: "numeric",
        maxLength: 16,
        required: true,
        enabled: true,
        editable: true,
        validations: [
          { rule: "required", message: "e-KTP number is required" },
          { rule: "pattern", value: "^[0-9]{16}$", message: "Must be exactly 16 digits" },
        ],
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "full_name",
        componentId: "full_name",
        label: "e-KTP name",
        name: "fullName",
        scope: "journeyState",
        placeholder: "Full name as on e-KTP",
        inputMode: "text",
        required: true,
        enabled: true,
        editable: true,
        validations: [{ rule: "required", message: "Full name is required" }],
        dynamic: {
          enabled: true,
          type: "VALUE",
          target: "defaultValue",
          source: { type: "FACT", path: "myInfoFullName" },
        },
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "place_of_birth",
        componentId: "place_of_birth",
        label: "Place of birth",
        name: "placeOfBirth",
        scope: "journeyState",
        placeholder: "Place of birth",
        inputMode: "text",
        required: true,
        enabled: true,
        editable: true,
        validations: [{ rule: "required", message: "Place of birth is required" }],
        span: 12,
      },
      {
        __component: "ui.date-input",
        testId: "date_of_birth",
        componentId: "date_of_birth",
        label: "Date of birth",
        name: "dateOfBirth",
        scope: "journeyState",
        placeholder: "Select date",
        displayFormat: "dd MMM yyyy",
        valueFormat: "yyyy-MM-dd",
        required: true,
        enabled: true,
        editable: true,
        validations: [{ rule: "required", message: "Date of birth is required" }],
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "gender",
        componentId: "gender",
        label: "Gender",
        name: "gender",
        scope: "journeyState",
        placeholder: "Select gender",
        required: true,
        enabled: true,
        editable: true,
        options: [
          { value: "male", label: "Male" },
          { value: "female", label: "Female" },
        ],
        validations: [{ rule: "required", message: "Gender is required" }],
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "marital_status",
        componentId: "marital_status",
        label: "Marital status",
        name: "maritalStatus",
        scope: "journeyState",
        placeholder: "Select marital status",
        enabled: true,
        editable: true,
        options: [
          { value: "single", label: "Single" },
          { value: "married", label: "Married" },
          { value: "divorced", label: "Divorced" },
          { value: "widowed", label: "Widowed" },
        ],
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "religion",
        componentId: "religion",
        label: "Religion",
        name: "religion",
        scope: "journeyState",
        placeholder: "Select religion",
        enabled: true,
        editable: true,
        options: [
          { value: "islam", label: "Islam" },
          { value: "christian", label: "Christian" },
          { value: "catholic", label: "Catholic" },
          { value: "hindu", label: "Hindu" },
          { value: "buddhist", label: "Buddhist" },
          { value: "confucian", label: "Confucian" },
          { value: "other", label: "Other" },
        ],
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "mothers_maiden_name",
        componentId: "mothers_maiden_name",
        label: "Mother\u2019s maiden name",
        name: "mothersMaidenName",
        scope: "journeyState",
        placeholder: "Enter mother\u2019s maiden name",
        inputMode: "text",
        required: true,
        enabled: true,
        editable: true,
        validations: [{ rule: "required", message: "Mother\u2019s maiden name is required" }],
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "address",
        componentId: "address",
        label: "Address",
        name: "address",
        scope: "journeyState",
        placeholder: "Street address",
        inputMode: "text",
        required: true,
        enabled: true,
        editable: true,
        validations: [{ rule: "required", message: "Address is required" }],
        span: 12,
      },
      {
        __component: "ui.dropdown",
        id: 302,
        label: "Province",
        placeholder: "Select province",
        searchable: false,
        testId: "ektp_review_province",
        span: 12,
        componentId: "ektp_review_province",
        name: "ektpReviewProvince",
        defaultValue: null,
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        cascadeResets: "ektpReviewCity,ektpReviewSubDistrict",
        dataSource: { url: "https://wilayah.id/api/provinces.json", dependsOn: null },
        validations: [
          {
            id: 500,
            rule: "required",
            value: null,
            message: "Province is required",
            ruleSet: null,
          },
        ],
        dynamic: null,
      },
      {
        __component: "ui.dropdown",
        id: 303,
        label: "City / Regency",
        placeholder: "Select city",
        searchable: false,
        testId: "ektp_review_city",
        span: 12,
        componentId: "ektp_review_city",
        name: "ektpReviewCity",
        defaultValue: null,
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        dependsOn: "ektpReviewProvince",
        cascadeResets: "ektpReviewSubDistrict",
        dataSource: { url: "https://wilayah.id/api/regencies/:code.json", dependsOn: "ektpReviewProvince" },
        validations: [
          {
            id: 501,
            rule: "required",
            value: null,
            message: "City is required",
            ruleSet: null,
          },
        ],
        dynamic: null,
      },
      {
        __component: "ui.dropdown",
        id: 304,
        label: "Sub-district",
        placeholder: "Select sub-district",
        searchable: false,
        testId: "ektp_review_sub_district",
        span: 12,
        componentId: "ektp_review_sub_district",
        name: "ektpReviewSubDistrict",
        defaultValue: null,
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        dependsOn: "ektpReviewCity",
        dataSource: { url: "https://wilayah.id/api/districts/:code.json", dependsOn: "ektpReviewCity" },
        validations: [
          {
            id: 502,
            rule: "required",
            value: null,
            message: "Sub-district is required",
            ruleSet: null,
          },
        ],
        dynamic: null,
      },
      {
        __component: "ui.text-input",
        testId: "rt",
        componentId: "rt",
        label: "RT",
        name: "rt",
        scope: "journeyState",
        placeholder: "000",
        inputMode: "numeric",
        enabled: true,
        editable: true,
        span: 6,
      },
      {
        __component: "ui.text-input",
        testId: "rw",
        componentId: "rw",
        label: "RW",
        name: "rw",
        scope: "journeyState",
        placeholder: "000",
        inputMode: "numeric",
        enabled: true,
        editable: true,
        span: 6,
      },
      {
        __component: "ui.text-input",
        testId: "postcode",
        componentId: "postcode",
        label: "Postcode",
        name: "postcode",
        scope: "journeyState",
        placeholder: "Postcode",
        inputMode: "numeric",
        enabled: true,
        editable: true,
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "occupation",
        componentId: "occupation",
        label: "Occupation",
        name: "occupation",
        scope: "journeyState",
        placeholder: "Select occupation",
        enabled: true,
        editable: true,
        options: [],
        dynamic: {
          enabled: true,
          type: "OPTIONS",
          target: "options",
          source: { type: "SERVICE", serviceCode: "GET_OCCUPATIONS" },
        },
        span: 12,
      },
      {
        __component: "ui.checkbox",
        testId: "ektp_terms",
        componentId: "ektp_terms",
        title: "Terms & Conditions",
        label:
          "I hereby declare that the data I have entered is accurate and matches the information related to my e-KTP.",
        name: "ektpTerms",
        scope: "journeyState",
        defaultValue: false,
        required: true,
        enabled: true,
        editable: true,
        validations: [{ rule: "required", message: "You must agree to the terms" }],
        span: 12,
      },
    ],
    footer: [
      nextButton(),
      {
        __component: "ui.button",
        testId: "retake_button",
        componentId: "retake_button",
        label: "Retake",
        name: "retakeButton",
        variant: "ghost",
        enabled: true,
        action: { type: "PREV_SCREEN" },
        span: 12,
      },
    ],
  },

  // // ── 6. Employment Details ─────────────────────────────────────────────────
  // {
  //   screenId: "employment_form",
  //   screenKey: "EMPLOYMENT_FORM",
  //   version: 1,
  //   meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
  //   header: [progressHeader(5), productNameText(), screenTitleText("Employment details")],
  //   body: [
  //     {
  //       __component: "ui.dropdown",
  //       testId: "employment_occupation",
  //       componentId: "employment_occupation",
  //       label: "Occupation",
  //       name: "employmentOccupation",
  //       scope: "journeyState",
  //       placeholder: "Select occupation",
  //       required: true,
  //       enabled: true,
  //       editable: true,
  //       options: [
  //         { value: "expert_admin", label: "Expert Administration" },
  //         { value: "employee", label: "Employee" },
  //         { value: "self_employed", label: "Self Employed" },
  //         { value: "professional", label: "Professional" },
  //         { value: "entrepreneur", label: "Entrepreneur" },
  //         { value: "retired", label: "Retired" },
  //         { value: "student", label: "Student" },
  //         { value: "housewife", label: "Housewife" },
  //         { value: "other", label: "Other" },
  //       ],
  //       validations: [{ rule: "required", message: "Occupation is required" }],
  //       dynamic: {
  //         enabled: true,
  //         type: "OPTIONS",
  //         target: "options",
  //         source: { type: "SERVICE", serviceCode: "GET_OCCUPATIONS" },
  //       },
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.dropdown-async",
  //       testId: "employment_industry",
  //       componentId: "employment_industry",
  //       label: "Industry category",
  //       name: "employmentIndustry",
  //       scope: "journeyState",
  //       placeholder: "Select industry",
  //       required: true,
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       dataSource: {
  //         endpoint: "/api/lookup/industries",
  //         method: "GET",
  //         mapping: { key: "code", label: "name" },
  //       },
  //       validations: [{ rule: "required", message: "Industry category is required" }],
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.text-input",
  //       testId: "employment_company_name",
  //       componentId: "employment_company_name",
  //       label: "Company name",
  //       name: "employmentCompanyName",
  //       scope: "journeyState",
  //       placeholder: "Enter company name",
  //       inputMode: "text",
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.text-input",
  //       testId: "employment_job_title",
  //       componentId: "employment_job_title",
  //       label: "Position / Job title",
  //       name: "employmentJobTitle",
  //       scope: "journeyState",
  //       placeholder: "Enter job title",
  //       inputMode: "text",
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.dropdown",
  //       testId: "employment_company_category",
  //       componentId: "employment_company_category",
  //       label: "Company category",
  //       name: "employmentCompanyCategory",
  //       scope: "journeyState",
  //       placeholder: "Select category",
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       options: [
  //         { value: "government", label: "Government" },
  //         { value: "private", label: "Private" },
  //         { value: "soe", label: "State-Owned Enterprise" },
  //       ],
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.dropdown",
  //       testId: "employment_status",
  //       componentId: "employment_status",
  //       label: "Employment status",
  //       name: "employmentStatus",
  //       scope: "journeyState",
  //       placeholder: "Select status",
  //       required: true,
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       options: [
  //         { value: "permanent", label: "Permanent" },
  //         { value: "contract", label: "Contract" },
  //         { value: "part_time", label: "Part Time" },
  //         { value: "probation", label: "Probation" },
  //       ],
  //       validations: [{ rule: "required", message: "Employment status is required" }],
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.text-input",
  //       testId: "employment_phone",
  //       componentId: "employment_phone",
  //       label: "Office phone number",
  //       name: "employmentPhone",
  //       scope: "journeyState",
  //       placeholder: "Enter phone number",
  //       prefix: "+62",
  //       inputMode: "phone",
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.date-input",
  //       testId: "employment_join_date",
  //       componentId: "employment_join_date",
  //       label: "Date joined",
  //       name: "employmentJoinDate",
  //       scope: "journeyState",
  //       placeholder: "Select date",
  //       displayFormat: "dd MMM yyyy",
  //       valueFormat: "yyyy-MM-dd",
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.text-input",
  //       testId: "employment_office_address",
  //       componentId: "employment_office_address",
  //       label: "Office address",
  //       name: "employmentOfficeAddress",
  //       scope: "journeyState",
  //       placeholder: "Street address",
  //       inputMode: "text",
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.dropdown-async",
  //       testId: "employment_province",
  //       componentId: "employment_province",
  //       label: "Province",
  //       name: "employmentProvince",
  //       scope: "journeyState",
  //       placeholder: "Select province",
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       dataSource: {
  //         endpoint: "/api/lookup/provinces",
  //         method: "GET",
  //         mapping: { key: "code", label: "name" },
  //       },
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.dropdown-async",
  //       testId: "employment_city",
  //       componentId: "employment_city",
  //       label: "City/Regency",
  //       name: "employmentCity",
  //       scope: "journeyState",
  //       placeholder: "Select city/regency",
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       dataSource: {
  //         endpoint: "/api/lookup/cities",
  //         method: "GET",
  //         params: { provinceCode: "${employmentProvince}" },
  //         mapping: { key: "code", label: "name" },
  //       },
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.dropdown-async",
  //       testId: "employment_sub_district",
  //       componentId: "employment_sub_district",
  //       label: "Sub-district/Village",
  //       name: "employmentSubDistrict",
  //       scope: "journeyState",
  //       placeholder: "Select sub-district/village",
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       dataSource: {
  //         endpoint: "/api/lookup/sub-districts",
  //         method: "GET",
  //         params: { cityCode: "${employmentCity}" },
  //         mapping: { key: "code", label: "name" },
  //       },
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.text-input",
  //       testId: "employment_rt",
  //       componentId: "employment_rt",
  //       label: "RT",
  //       name: "employmentRt",
  //       scope: "journeyState",
  //       placeholder: "000",
  //       inputMode: "numeric",
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       span: 6,
  //     },
  //     {
  //       __component: "ui.text-input",
  //       testId: "employment_rw",
  //       componentId: "employment_rw",
  //       label: "RW",
  //       name: "employmentRw",
  //       scope: "journeyState",
  //       placeholder: "000",
  //       inputMode: "numeric",
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       span: 6,
  //     },
  //     {
  //       __component: "ui.text-input",
  //       testId: "employment_postcode",
  //       componentId: "employment_postcode",
  //       label: "Postcode",
  //       name: "employmentPostcode",
  //       scope: "journeyState",
  //       placeholder: "Postcode",
  //       inputMode: "numeric",
  //       enabled: true,
  //       editable: true,
  //       toggleField: true,
  //       toggleFieldReff: "employmentOccupation",
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.checkbox",
  //       testId: "employment_declaration",
  //       componentId: "employment_declaration",
  //       title: "Declaration:",
  //       label:
  //         "I hereby declare that I have no relationship with any government/state officials, politicians or public figures.",
  //       name: "employmentDeclaration",
  //       scope: "journeyState",
  //       defaultValue: false,
  //       required: true,
  //       enabled: true,
  //       editable: true,
  //       validations: [{ rule: "required", message: "You must agree to this declaration" }],
  //       span: 12,
  //     },
  //   ],
  //   footer: [nextButton()],
  // },

  // // ── 7. Confirmation ───────────────────────────────────────────────────────
  // {
  //   screenId: "confirmation",
  //   screenKey: "CONFIRMATION",
  //   version: 1,
  //   meta: { label: "Confirmation", enableBackButton: true, enableCloseButton: true },
  //   header: [
  //     progressHeader(7),
  //     screenSubtitleText("screen_subtitle", "Apply for"),
  //     screenTitleText("Global Access Account \u2014 Savings Account"),
  //   ],
  //   body: [
  //     {
  //       __component: "ui.checkbox",
  //       testId: "redemption_code_toggle",
  //       componentId: "redemption_code_toggle",
  //       label: "Apply redemption code",
  //       name: "hasRedemptionCode",
  //       scope: "journeyState",
  //       defaultValue: false,
  //       enabled: true,
  //       editable: true,
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.review-card",
  //       testId: "contact_details_card",
  //       componentId: "contact_details_card",
  //       name: "contactDetailsCard",
  //       label: "Contact details",
  //       enabled: true,
  //       items: [
  //         { id: "mobileNumber", label: "Mobile number", path: "mobileNumber" },
  //         { id: "emailAddress", label: "Email address", path: "emailAddress" },
  //       ],
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.review-card",
  //       testId: "ektp_details_card",
  //       componentId: "ektp_details_card",
  //       name: "ektpDetailsCard",
  //       label: "e-KTP details",
  //       enabled: true,
  //       items: [
  //         { id: "ektpNumber", label: "e-KTP number", path: "ektpNumber" },
  //         { id: "fullName", label: "Full name", path: "fullName" },
  //         { id: "dateOfBirth", label: "Date of birth", path: "dateOfBirth" },
  //         { id: "placeOfBirth", label: "Place of birth", path: "placeOfBirth" },
  //         { id: "gender", label: "Gender", path: "gender" },
  //         { id: "religion", label: "Religion", path: "religion" },
  //         { id: "maritalStatus", label: "Marital status", path: "maritalStatus" },
  //         { id: "mothersMaidenName", label: "Mother\u2019s maiden name", path: "mothersMaidenName" },
  //         { id: "occupation", label: "Occupation", path: "occupation" },
  //         { id: "address", label: "Address", path: "address" },
  //         { id: "province", label: "Province", path: "province" },
  //         { id: "cityRegency", label: "City/Regency", path: "cityRegency" },
  //         { id: "subDistrict", label: "Sub-district", path: "subDistrict" },
  //         { id: "rtRw", label: "RT / RW", path: "rt" },
  //         { id: "postcode", label: "Postcode", path: "postcode" },
  //       ],
  //       span: 12,
  //     },
  //     {
  //       __component: "ui.review-card",
  //       testId: "employment_details_card",
  //       componentId: "employment_details_card",
  //       name: "employmentDetailsCard",
  //       label: "Employment details",
  //       enabled: true,
  //       items: [
  //         { id: "employmentOccupation", label: "Occupation", path: "employmentOccupation" },
  //         { id: "employmentIndustry", label: "Industry", path: "employmentIndustry" },
  //         { id: "employmentCompanyName", label: "Company", path: "employmentCompanyName" },
  //         { id: "employmentJobTitle", label: "Job title", path: "employmentJobTitle" },
  //         { id: "employmentCompanyCategory", label: "Company category", path: "employmentCompanyCategory" },
  //         { id: "employmentStatus", label: "Status", path: "employmentStatus" },
  //         { id: "employmentPhone", label: "Office phone", path: "employmentPhone" },
  //         { id: "employmentJoinDate", label: "Join date", path: "employmentJoinDate" },
  //         { id: "employmentOfficeAddress", label: "Office address", path: "employmentOfficeAddress" },
  //         { id: "employmentProvince", label: "Province", path: "employmentProvince" },
  //         { id: "employmentCity", label: "City/Regency", path: "employmentCity" },
  //         { id: "employmentSubDistrict", label: "Sub-district", path: "employmentSubDistrict" },
  //         { id: "employmentPostcode", label: "Postcode", path: "employmentPostcode" },
  //       ],
  //       span: 12,
  //     },
  //   ],
  //   footer: [
  //     {
  //       __component: "ui.slide-to-confirm",
  //       testId: "slide_confirm",
  //       componentId: "slide_confirm",
  //       label: "Slide to confirm",
  //       name: "slideConfirm",
  //       action: {
  //         key: "submitApplication",
  //         type: "submit_journey",
  //         payload: { serviceCode: "CA_SUBMIT" },
  //       },
  //       span: 12,
  //     },
  //   ],
  // },
];

// ---------------------------------------------------------------------------
// Seed entry point
// ---------------------------------------------------------------------------

export async function seedApplyCaV3(strapi: StrapiInstance) {
  console.log("[seed-v3] Starting apply-ca-v3 seed\u2026");

  for (const screenData of screens) {
    await createAndPublishScreen(strapi, screenData);
  }

  console.log("[seed-v3] Done.");
}
