/**
 * Seed v2: Apply Current Account — Mobile Number & Email screens
 *
 * Populates screens using the new component structure:
 *   - binding: sdui.binding component — maps field value to journeyState by path
 *   - validations: sdui.validation[] repeatable — typed rules (required, pattern, match, etc.)
 *   - ui.progress-bar in header, ui.divider in footer
 *   - meta uses enableBackButton / enableCloseButton
 *
 * Usage (via bootstrap):
 *   SEED_DATA=apply-ca-v2 npm run develop
 */

import type { Core } from "@strapi/strapi";

type StrapiInstance = Core.Strapi;

async function findScreen(strapi: StrapiInstance, screenId: string) {
  const results = await strapi.documents("api::screen.screen").findMany({
    filters: { screenId: { $eq: screenId } },
    status: "draft",
    limit: 1,
  });
  return results[0] ?? null;
}

async function createAndPublishScreen(strapi: StrapiInstance, data: Record<string, unknown>) {
  const screenId = data.screenId as string;
  const existing = await findScreen(strapi, screenId);

  if (existing) {
    console.log(`[seed-v2] Screen already exists — skipping: ${screenId}`);
    return existing;
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const created = await strapi.documents("api::screen.screen").create({ data: data as any });
  await strapi.documents("api::screen.screen").publish({ documentId: created.documentId });

  console.log(`[seed-v2] ✓ Screen created & published: ${screenId}`);
  return created;
}

// ---------------------------------------------------------------------------
// Screen definitions
// ---------------------------------------------------------------------------

const screens = [
  {
    screenId: "mobile_number_form",
    screenKey: "MOBILE_NUMBER_FORM",
    version: 1,
    meta: {
      label: "Apply",
      enableBackButton: false,
      enableCloseButton: true,
    },
    header: [
      {
        __component: "ui.progress-bar",
        testId: "progress_bar",
        componentId: "progress_bar",
        name: "progressBar",
        currentStep: 1,
        maxStep: 11,
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "product_name",
        componentId: "product_name",
        label: "",
        name: "productName",
        variant: "subtitle",
        enabled: true,
        visible: true,
        valueSource: { type: "binding", path: "product.name" },
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_title",
        componentId: "screen_title",
        label: "Enter your mobile number",
        name: "screenTitle",
        variant: "title",
        enabled: true,
        visible: true,
        span: 12,
      },
    ],
    body: [
      {
        __component: "ui.text-input",
        testId: "mobile_number",
        componentId: "mobile_number",
        label: "Mobile number",
        name: "mobileNumber",
        placeholder: "Enter mobile number",
        prefix: "+62",
        inputMode: "numeric",
        defaultValue: "",
        maxLength: 13,
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "mobileNumber", scope: "journeyState" },
        validations: [
          { rule: "required", message: "Mobile number is required" },
          { rule: "pattern", value: "^[0-9]{8,13}$", message: "Enter a valid Indonesian mobile number" },
        ],
        dynamic: {
          enabled: true,
          type: "VALUE",
          target: "defaultValue",
          source: { type: "FACT", path: "existingMobileNumber" },
        },
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "disclaimer_label",
        componentId: "disclaimer_label",
        label: "Disclaimer:",
        name: "disclaimerLabel",
        variant: "label",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "disclaimer_text",
        componentId: "disclaimer_text",
        label:
          "Maybank collects your mobile number for purposes including, but not limited to, security feature activation, ATM card activation, sending SMS TAC codes and Mobile App registration. SMS TACs will be sent to your registered mobile number. Your information will be stored securely in Maybank's system, which protects the confidentiality of customer data.",
        name: "disclaimerText",
        variant: "body",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.checkbox",
        testId: "mobile_consent",
        componentId: "mobile_consent",
        title: "I hereby declare:",
        label:
          "I have read and understood the above use of my mobile number. I agree to provide my mobile number and consent to it being used for these purposes.",
        name: "mobileConsent",
        defaultValue: false,
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "mobileConsent", scope: "journeyState" },
        validations: [{ rule: "required", message: "You must agree to continue" }],
        span: 12,
      },
    ],
    footer: [
      {
        __component: "ui.button",
        testId: "next_button",
        componentId: "next_button",
        label: "Next",
        name: "nextButton",
        variant: "primary",
        enabled: true,
        visible: true,
        action: { type: "NEXT_SCREEN" },
        span: 12,
      },
    ],
  },

  {
    screenId: "email_form",
    screenKey: "EMAIL_FORM",
    version: 1,
    meta: {
      label: "Apply",
      enableBackButton: true,
      enableCloseButton: true,
    },
    header: [
      {
        __component: "ui.progress-bar",
        testId: "progress_bar",
        componentId: "progress_bar",
        name: "progressBar",
        currentStep: 2,
        maxStep: 11,
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "product_name",
        componentId: "product_name",
        label: "",
        name: "productName",
        variant: "subtitle",
        enabled: true,
        visible: true,
        valueSource: { type: "binding", path: "product.name" },
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_title",
        componentId: "screen_title",
        label: "Your email address",
        name: "screenTitle",
        variant: "title",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_subtitle",
        componentId: "screen_subtitle",
        label: "Fill in your email address",
        name: "screenSubtitle",
        variant: "subtitle",
        enabled: true,
        visible: true,
        span: 12,
      },
    ],
    body: [
      {
        __component: "ui.text-input",
        testId: "email_address",
        componentId: "email_address",
        label: "Email address",
        name: "emailAddress",
        placeholder: "Enter email address",
        inputMode: "email",
        defaultValue: "",
        maxLength: 200,
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "emailAddress", scope: "journeyState" },
        validations: [
          { rule: "required", message: "Email address is required" },
          { rule: "pattern", value: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$", message: "Enter a valid email address" },
        ],
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "confirm_email_address",
        componentId: "confirm_email_address",
        label: "Confirm email address",
        name: "confirmEmailAddress",
        placeholder: "Re-enter email address",
        inputMode: "email",
        defaultValue: "",
        maxLength: 200,
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "confirmEmailAddress", scope: "journeyState" },
        validations: [
          { rule: "required", message: "Confirm email address is required" },
          { rule: "match", value: "emailAddress", message: "Email addresses do not match" },
        ],
        span: 12,
      },
    ],
    footer: [
      {
        __component: "ui.button",
        testId: "next_button",
        componentId: "next_button",
        label: "Next",
        name: "nextButton",
        variant: "primary",
        enabled: true,
        visible: true,
        action: { type: "NEXT_SCREEN" },
        span: 12,
      },
      {
        __component: "ui.divider",
        testId: "footer_divider",
        componentId: "footer_divider",
        label: "Or continue with an account",
        name: "footerDivider",
        visible: true,
        span: 12,
      },
      {
        __component: "ui.button",
        testId: "google_account_button",
        componentId: "google_account_button",
        label: "Continue with Google",
        name: "googleAccountButton",
        variant: "secondary",
        enabled: true,
        visible: true,
        icon: { name: "googleLogo", position: "left" },
        action: { type: "SOCIAL_LOGIN", provider: "GOOGLE" },
        span: 12,
      },
      {
        __component: "ui.button",
        testId: "apple_account_button",
        componentId: "apple_account_button",
        label: "Continue with Apple",
        name: "appleAccountButton",
        variant: "secondary",
        enabled: true,
        visible: true,
        icon: { name: "appleLogo", position: "left" },
        action: { type: "SOCIAL_LOGIN", provider: "APPLE" },
        span: 12,
      },
    ],
  },

  {
    screenId: "ektp_instructions",
    screenKey: "EKTP_INSTRUCTIONS",
    version: 1,
    meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
    header: [
      {
        __component: "ui.progress-bar",
        testId: "progress_bar",
        componentId: "progress_bar",
        name: "progressBar",
        currentStep: 3,
        maxStep: 11,
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "product_name",
        componentId: "product_name",
        label: "",
        name: "productName",
        variant: "subtitle",
        enabled: true,
        visible: true,
        valueSource: { type: "binding", path: "product.name" },
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_title",
        componentId: "screen_title",
        label: "e-KTP photo conditions",
        name: "screenTitle",
        variant: "title",
        enabled: true,
        visible: true,
        span: 12,
      },
    ],
    body: [
      {
        __component: "ui.text",
        testId: "hint_1",
        componentId: "hint_1",
        label: "Ensure your face is clearly visible",
        name: "hint1",
        variant: "body",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "hint_2",
        componentId: "hint_2",
        label: "Capture a clear photo of your e-KTP so the system can identify your identity",
        name: "hint2",
        variant: "body",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "hint_3",
        componentId: "hint_3",
        label: "Ensure all text on the e-KTP is clearly readable",
        name: "hint3",
        variant: "body",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "hint_4",
        componentId: "hint_4",
        label: "Do not alter or edit the e-KTP image in any way",
        name: "hint4",
        variant: "body",
        enabled: true,
        visible: true,
        span: 12,
      },
    ],
    footer: [
      {
        __component: "ui.button",
        testId: "start_button",
        componentId: "start_button",
        label: "Get started",
        name: "startButton",
        variant: "primary",
        enabled: true,
        visible: true,
        action: { type: "NEXT_SCREEN" },
        span: 12,
      },
    ],
  },

  {
    screenId: "ektp_capture",
    screenKey: "EKTP_CAPTURE",
    version: 1,
    meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
    body: [
      {
        __component: "ui.camera-capture",
        testId: "ektp_camera",
        componentId: "ektp_camera",
        name: "ektpCamera",
        overlayShape: "rectangle",
        overlayAspect: "1.586",
        overlayHint: "Please ensure your e-KTP details are visible in the frame",
        binding: { path: "ektpImage", scope: "journeyState" },
        onComplete: {
          action: {
            key: "ektpCaptured",
            type: "api_call",
            payload: { serviceCode: "OCR_EKTP", actionId: "ektp-captured" },
          },
        },
        span: 12,
      },
    ],
    footer: [],
  },

  {
    screenId: "ektp_review",
    screenKey: "EKTP_REVIEW",
    version: 1,
    meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
    header: [
      {
        __component: "ui.progress-bar",
        testId: "progress_bar",
        componentId: "progress_bar",
        name: "progressBar",
        currentStep: 3,
        maxStep: 11,
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.image-preview",
        testId: "ektp_preview",
        componentId: "ektp_preview",
        name: "ektpPreview",
        enabled: true,
        editable: false,
        visible: true,
        valueSource: { type: "journeyState", path: "ektpImage" },
        span: 12,
      },
    ],
    body: [
      {
        __component: "ui.text",
        testId: "screen_title",
        componentId: "screen_title",
        label: "Review your e-KTP details",
        name: "screenTitle",
        variant: "title",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_subtitle",
        componentId: "screen_subtitle",
        label: "Make sure all details are correct before proceeding",
        name: "screenSubtitle",
        variant: "subtitle",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "ektp_number",
        componentId: "ektp_number",
        label: "e-KTP number",
        name: "ektpNumber",
        placeholder: "16-digit KTP number",
        inputMode: "numeric",
        maxLength: 16,
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "ektpNumber", scope: "journeyState" },
        validations: [
          { rule: "required", message: "e-KTP number is required" },
          { rule: "pattern", value: "^[0-9]{16}$", message: "Must be exactly 16 digits" },
        ],
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "full_name",
        componentId: "full_name",
        label: "Full name",
        name: "fullName",
        placeholder: "Full name as on e-KTP",
        inputMode: "text",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "fullName", scope: "journeyState" },
        validations: [{ rule: "required", message: "Full name is required" }],
        dynamic: {
          enabled: true,
          type: "VALUE",
          target: "defaultValue",
          source: { type: "FACT", path: "myInfoFullName" },
        },
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "place_of_birth",
        componentId: "place_of_birth",
        label: "Place of birth",
        name: "placeOfBirth",
        placeholder: "Place of birth",
        inputMode: "text",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "placeOfBirth", scope: "journeyState" },
        validations: [{ rule: "required", message: "Place of birth is required" }],
        span: 12,
      },
      {
        __component: "ui.date-input",
        testId: "date_of_birth",
        componentId: "date_of_birth",
        label: "Date of birth",
        name: "dateOfBirth",
        placeholder: "Select date",
        displayFormat: "dd MMM yyyy",
        valueFormat: "yyyy-MM-dd",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "dateOfBirth", scope: "journeyState" },
        validations: [{ rule: "required", message: "Date of birth is required" }],
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "gender",
        componentId: "gender",
        label: "Gender",
        name: "gender",
        placeholder: "Select gender",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        options: [
          { value: "male", label: "Male" },
          { value: "female", label: "Female" },
        ],
        binding: { path: "gender", scope: "journeyState" },
        validations: [{ rule: "required", message: "Gender is required" }],
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "religion",
        componentId: "religion",
        label: "Religion",
        name: "religion",
        placeholder: "Select religion",
        enabled: true,
        editable: true,
        visible: true,
        options: [
          { value: "islam", label: "Islam" },
          { value: "christian", label: "Christian" },
          { value: "catholic", label: "Catholic" },
          { value: "hindu", label: "Hindu" },
          { value: "buddhist", label: "Buddhist" },
          { value: "confucian", label: "Confucian" },
          { value: "other", label: "Other" },
        ],
        binding: { path: "religion", scope: "journeyState" },
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "marital_status",
        componentId: "marital_status",
        label: "Marital status",
        name: "maritalStatus",
        placeholder: "Select marital status",
        enabled: true,
        editable: true,
        visible: true,
        options: [
          { value: "single", label: "Single" },
          { value: "married", label: "Married" },
          { value: "divorced", label: "Divorced" },
          { value: "widowed", label: "Widowed" },
        ],
        binding: { path: "maritalStatus", scope: "journeyState" },
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "address",
        componentId: "address",
        label: "Address",
        name: "address",
        placeholder: "Street address",
        inputMode: "text",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "address", scope: "journeyState" },
        validations: [{ rule: "required", message: "Address is required" }],
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "rt",
        componentId: "rt",
        label: "RT",
        name: "rt",
        placeholder: "000",
        inputMode: "numeric",
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "rt", scope: "journeyState" },
        span: 6,
      },
      {
        __component: "ui.text-input",
        testId: "rw",
        componentId: "rw",
        label: "RW",
        name: "rw",
        placeholder: "000",
        inputMode: "numeric",
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "rw", scope: "journeyState" },
        span: 6,
      },
      {
        __component: "ui.text-input",
        testId: "postcode",
        componentId: "postcode",
        label: "Postcode",
        name: "postcode",
        placeholder: "Postcode",
        inputMode: "numeric",
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "postcode", scope: "journeyState" },
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "occupation",
        componentId: "occupation",
        label: "Occupation",
        name: "occupation",
        placeholder: "Select occupation",
        enabled: true,
        editable: true,
        visible: true,
        options: [],
        binding: { path: "occupation", scope: "journeyState" },
        span: 12,
      },
    ],
    footer: [
      {
        __component: "ui.button",
        testId: "next_button",
        componentId: "next_button",
        label: "Next",
        name: "nextButton",
        variant: "primary",
        enabled: true,
        visible: true,
        action: { type: "NEXT_SCREEN" },
        span: 12,
      },
      {
        __component: "ui.button",
        testId: "retake_button",
        componentId: "retake_button",
        label: "Retake",
        name: "retakeButton",
        variant: "ghost",
        enabled: true,
        visible: true,
        action: { type: "PREV_SCREEN" },
        span: 12,
      },
    ],
  },

  {
    screenId: "npwp_form",
    screenKey: "NPWP_FORM",
    version: 1,
    meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
    header: [
      {
        __component: "ui.progress-bar",
        testId: "progress_bar",
        componentId: "progress_bar",
        name: "progressBar",
        currentStep: 4,
        maxStep: 11,
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "product_name",
        componentId: "product_name",
        label: "",
        name: "productName",
        variant: "subtitle",
        enabled: true,
        visible: true,
        valueSource: { type: "binding", path: "product.name" },
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_title",
        componentId: "screen_title",
        label: "NPWP details",
        name: "screenTitle",
        variant: "title",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_subtitle",
        componentId: "screen_subtitle",
        label: "Enter your NPWP information. This is optional.",
        name: "screenSubtitle",
        variant: "subtitle",
        enabled: true,
        visible: true,
        span: 12,
      },
    ],
    body: [
      {
        __component: "ui.text-input",
        testId: "npwp_number",
        componentId: "npwp_number",
        label: "NPWP number",
        name: "npwpNumber",
        placeholder: "Optional",
        inputMode: "numeric",
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "npwpNumber", scope: "journeyState" },
        span: 12,
      },
      {
        __component: "ui.link",
        testId: "nik_npwp_link",
        componentId: "nik_npwp_link",
        label: "Perform NIK – NPWP Matching",
        name: "nikNpwpLink",
        action: {
          key: "nikNpwpMatch",
          type: "api_call",
          payload: { serviceCode: "NIK_NPWP_MATCH" },
        },
        span: 12,
      },
      {
        __component: "ui.rich-text",
        testId: "npwp_disclaimer",
        componentId: "npwp_disclaimer",
        name: "npwpDisclaimer",
        content: [
          {
            type: "paragraph",
            children: [
              {
                type: "text",
                text: "In line with the Ministry of Finance Regulation No. 112/2022, resident individual taxpayers (Indonesian citizens and foreign nationals with a valid identity card) use their National Identification Number (NIK) as their Taxpayer Identification Number (NPWP).",
              },
            ],
          },
        ],
        span: 12,
      },
    ],
    footer: [
      {
        __component: "ui.button",
        testId: "next_button",
        componentId: "next_button",
        label: "Next",
        name: "nextButton",
        variant: "primary",
        enabled: true,
        visible: true,
        action: { type: "NEXT_SCREEN" },
        span: 12,
      },
    ],
  },
  {
    screenId: "employment_form",
    screenKey: "EMPLOYMENT_FORM",
    version: 1,
    meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
    header: [
      {
        __component: "ui.progress-bar",
        testId: "progress_bar",
        componentId: "progress_bar",
        name: "progressBar",
        currentStep: 5,
        maxStep: 11,
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "product_name",
        componentId: "product_name",
        label: "",
        name: "productName",
        variant: "subtitle",
        enabled: true,
        visible: true,
        valueSource: { type: "binding", path: "product.name" },
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_title",
        componentId: "screen_title",
        label: "Employment details",
        name: "screenTitle",
        variant: "title",
        enabled: true,
        visible: true,
        span: 12,
      },
    ],
    body: [
      {
        __component: "ui.dropdown",
        testId: "employment_occupation",
        componentId: "employment_occupation",
        label: "Occupation",
        name: "employmentOccupation",
        placeholder: "Select occupation",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        options: [
          { value: "expert_admin", label: "Expert Administration" },
          { value: "employee", label: "Employee" },
          { value: "self_employed", label: "Self Employed" },
          { value: "professional", label: "Professional" },
          { value: "entrepreneur", label: "Entrepreneur" },
          { value: "retired", label: "Retired" },
          { value: "student", label: "Student" },
          { value: "housewife", label: "Housewife" },
          { value: "other", label: "Other" },
        ],
        binding: { path: "employmentOccupation", scope: "journeyState" },
        validations: [{ rule: "required", message: "Occupation is required" }],
        dynamic: {
          enabled: true,
          type: "OPTIONS",
          target: "options",
          source: { type: "SERVICE", serviceCode: "GET_OCCUPATIONS" },
        },
        span: 12,
      },
      {
        __component: "ui.dropdown-async",
        testId: "employment_industry",
        componentId: "employment_industry",
        label: "Industry category",
        name: "employmentIndustry",
        placeholder: "Select industry",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        dataSource: {
          endpoint: "/api/lookup/industries",
          method: "GET",
          mapping: { key: "code", label: "name" },
        },
        binding: { path: "employmentIndustry", scope: "journeyState" },
        validations: [{ rule: "required", message: "Industry category is required" }],
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "employment_company_name",
        componentId: "employment_company_name",
        label: "Company name",
        name: "employmentCompanyName",
        placeholder: "Enter company name",
        inputMode: "text",
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "employmentCompanyName", scope: "journeyState" },
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "employment_job_title",
        componentId: "employment_job_title",
        label: "Position / Job title",
        name: "employmentJobTitle",
        placeholder: "Enter job title",
        inputMode: "text",
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "employmentJobTitle", scope: "journeyState" },
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "employment_company_category",
        componentId: "employment_company_category",
        label: "Company category",
        name: "employmentCompanyCategory",
        placeholder: "Select category",
        enabled: true,
        editable: true,
        visible: true,
        options: [
          { value: "government", label: "Government" },
          { value: "private", label: "Private" },
          { value: "soe", label: "State-Owned Enterprise" },
        ],
        binding: { path: "employmentCompanyCategory", scope: "journeyState" },
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "employment_status",
        componentId: "employment_status",
        label: "Employment status",
        name: "employmentStatus",
        placeholder: "Select status",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        options: [
          { value: "permanent", label: "Permanent" },
          { value: "contract", label: "Contract" },
          { value: "part_time", label: "Part Time" },
          { value: "probation", label: "Probation" },
        ],
        binding: { path: "employmentStatus", scope: "journeyState" },
        validations: [{ rule: "required", message: "Employment status is required" }],
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "employment_phone",
        componentId: "employment_phone",
        label: "Office phone number",
        name: "employmentPhone",
        placeholder: "+62",
        inputMode: "phone",
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "employmentPhone", scope: "journeyState" },
        span: 12,
      },
      {
        __component: "ui.date-input",
        testId: "employment_join_date",
        componentId: "employment_join_date",
        label: "Date joined",
        name: "employmentJoinDate",
        placeholder: "Select date",
        displayFormat: "dd MMM yyyy",
        valueFormat: "yyyy-MM-dd",
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "employmentJoinDate", scope: "journeyState" },
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "employment_office_address",
        componentId: "employment_office_address",
        label: "Office address",
        name: "employmentOfficeAddress",
        placeholder: "Street address",
        inputMode: "text",
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "employmentOfficeAddress", scope: "journeyState" },
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "employment_rt",
        componentId: "employment_rt",
        label: "RT",
        name: "employmentRt",
        placeholder: "000",
        inputMode: "numeric",
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "employmentRt", scope: "journeyState" },
        span: 6,
      },
      {
        __component: "ui.text-input",
        testId: "employment_rw",
        componentId: "employment_rw",
        label: "RW",
        name: "employmentRw",
        placeholder: "000",
        inputMode: "numeric",
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "employmentRw", scope: "journeyState" },
        span: 6,
      },
      {
        __component: "ui.text-input",
        testId: "employment_postcode",
        componentId: "employment_postcode",
        label: "Postcode",
        name: "employmentPostcode",
        placeholder: "Postcode",
        inputMode: "numeric",
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "employmentPostcode", scope: "journeyState" },
        span: 12,
      },
    ],
    footer: [
      {
        __component: "ui.button",
        testId: "next_button",
        componentId: "next_button",
        label: "Next",
        name: "nextButton",
        variant: "primary",
        enabled: true,
        visible: true,
        action: { type: "NEXT_SCREEN" },
        span: 12,
      },
    ],
  },
  {
    screenId: "financial_form",
    screenKey: "FINANCIAL_FORM",
    version: 1,
    meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
    header: [
      {
        __component: "ui.progress-bar",
        testId: "progress_bar",
        componentId: "progress_bar",
        name: "progressBar",
        currentStep: 6,
        maxStep: 11,
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "product_name",
        componentId: "product_name",
        label: "",
        name: "productName",
        variant: "subtitle",
        enabled: true,
        visible: true,
        valueSource: { type: "binding", path: "product.name" },
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_title",
        componentId: "screen_title",
        label: "Financial details",
        name: "screenTitle",
        variant: "title",
        enabled: true,
        visible: true,
        span: 12,
      },
    ],
    body: [
      {
        __component: "ui.dropdown",
        testId: "source_of_income",
        componentId: "source_of_income",
        label: "Source of income",
        name: "sourceOfIncome",
        placeholder: "Select source",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        options: [
          { value: "salary", label: "Salary" },
          { value: "business", label: "Business" },
          { value: "investment", label: "Investment" },
          { value: "pension", label: "Pension" },
          { value: "other", label: "Other" },
        ],
        binding: { path: "sourceOfIncome", scope: "journeyState" },
        validations: [{ rule: "required", message: "Source of income is required" }],
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "number_of_dependents",
        componentId: "number_of_dependents",
        label: "Number of dependents",
        name: "numberOfDependents",
        placeholder: "Select",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        options: [
          { value: "0", label: "0" },
          { value: "lt100", label: "Less than 100" },
          { value: "gte100", label: "100 or more" },
        ],
        binding: { path: "numberOfDependents", scope: "journeyState" },
        validations: [{ rule: "required", message: "Number of dependents is required" }],
        span: 12,
      },
      {
        __component: "ui.money-input",
        testId: "monthly_income",
        componentId: "monthly_income",
        label: "Monthly income",
        name: "monthlyIncome",
        currency: "IDR",
        binding: { path: "monthlyIncome", scope: "journeyState" },
        validations: [{ rule: "required", message: "Monthly income is required" }],
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "purpose_of_funds",
        componentId: "purpose_of_funds",
        label: "Purpose of funds",
        name: "purposeOfFunds",
        placeholder: "Select purpose",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        options: [
          { value: "savings", label: "Savings" },
          { value: "investment", label: "Investment" },
          { value: "business", label: "Business" },
          { value: "education", label: "Education" },
          { value: "other", label: "Other" },
        ],
        binding: { path: "purposeOfFunds", scope: "journeyState" },
        validations: [{ rule: "required", message: "Purpose of funds is required" }],
        span: 12,
      },
      {
        __component: "ui.money-input",
        testId: "monthly_transaction_amount",
        componentId: "monthly_transaction_amount",
        label: "Monthly transaction amount",
        name: "monthlyTransactionAmount",
        currency: "IDR",
        binding: { path: "monthlyTransactionAmount", scope: "journeyState" },
        validations: [{ rule: "required", message: "Monthly transaction amount is required" }],
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "monthly_transaction_frequency",
        componentId: "monthly_transaction_frequency",
        label: "Monthly transaction frequency",
        name: "monthlyTransactionFrequency",
        placeholder: "Select range",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        options: [
          { value: "lt10", label: "IDR 0 – 10 Million" },
          { value: "lt20", label: "IDR 10 – 20 Million" },
          { value: "gte20", label: "IDR 20 Million+" },
        ],
        binding: { path: "monthlyTransactionFrequency", scope: "journeyState" },
        validations: [{ rule: "required", message: "Monthly transaction frequency is required" }],
        span: 12,
      },
    ],
    footer: [
      {
        __component: "ui.button",
        testId: "next_button",
        componentId: "next_button",
        label: "Next",
        name: "nextButton",
        variant: "primary",
        enabled: true,
        visible: true,
        action: { type: "NEXT_SCREEN" },
        span: 12,
      },
    ],
  },

  {
    screenId: "residential_form",
    screenKey: "RESIDENTIAL_FORM",
    version: 1,
    meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
    header: [
      {
        __component: "ui.progress-bar",
        testId: "progress_bar",
        componentId: "progress_bar",
        name: "progressBar",
        currentStep: 7,
        maxStep: 11,
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "product_name",
        componentId: "product_name",
        label: "",
        name: "productName",
        variant: "subtitle",
        enabled: true,
        visible: true,
        valueSource: { type: "binding", path: "product.name" },
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_title",
        componentId: "screen_title",
        label: "Residential details",
        name: "screenTitle",
        variant: "title",
        enabled: true,
        visible: true,
        span: 12,
      },
    ],
    body: [
      {
        __component: "ui.dropdown",
        testId: "residential_address_source",
        componentId: "residential_address_source",
        label: "Select residential address",
        name: "residentialAddressSource",
        placeholder: "Select",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        options: [
          { value: "same_as_ktp", label: "Same as e-KTP address" },
          { value: "other", label: "Other address" },
        ],
        binding: { path: "residentialAddressSource", scope: "journeyState" },
        validations: [{ rule: "required", message: "Please select your residential address" }],
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "residential_address",
        componentId: "residential_address",
        label: "Address",
        name: "residentialAddress",
        placeholder: "Street address",
        inputMode: "text",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "residentialAddress", scope: "journeyState" },
        validations: [{ rule: "required", message: "Residential address is required" }],
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "residential_ownership_status",
        componentId: "residential_ownership_status",
        label: "Residential ownership status",
        name: "residentialOwnershipStatus",
        placeholder: "Select status",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        options: [
          { value: "owner", label: "Owner" },
          { value: "renter", label: "Renter" },
          { value: "family", label: "Family" },
        ],
        binding: { path: "residentialOwnershipStatus", scope: "journeyState" },
        validations: [{ rule: "required", message: "Ownership status is required" }],
        span: 12,
      },
      {
        __component: "ui.dropdown",
        testId: "correspondence_address_source",
        componentId: "correspondence_address_source",
        label: "Correspondence address",
        name: "correspondenceAddressSource",
        placeholder: "Select",
        enabled: true,
        editable: true,
        visible: true,
        options: [
          { value: "same_as_ktp", label: "Same as e-KTP address" },
          { value: "same_as_residential", label: "Same as residential address" },
          { value: "other", label: "Other address" },
        ],
        binding: { path: "correspondenceAddressSource", scope: "journeyState" },
        span: 12,
      },
      {
        __component: "ui.text-input",
        testId: "correspondence_address",
        componentId: "correspondence_address",
        label: "Correspondence address",
        name: "correspondenceAddress",
        placeholder: "Street address",
        inputMode: "text",
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "correspondenceAddress", scope: "journeyState" },
        validations: [{ rule: "required", message: "Correspondence address is required" }],
        span: 12,
      },
    ],
    footer: [
      {
        __component: "ui.button",
        testId: "next_button",
        componentId: "next_button",
        label: "Next",
        name: "nextButton",
        variant: "primary",
        enabled: true,
        visible: true,
        action: { type: "NEXT_SCREEN" },
        span: 12,
      },
    ],
  },

  {
    screenId: "ekyc_instructions",
    screenKey: "EKYC_INSTRUCTIONS",
    version: 1,
    meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
    header: [
      {
        __component: "ui.progress-bar",
        testId: "progress_bar",
        componentId: "progress_bar",
        name: "progressBar",
        currentStep: 8,
        maxStep: 11,
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "product_name",
        componentId: "product_name",
        label: "",
        name: "productName",
        variant: "subtitle",
        enabled: true,
        visible: true,
        valueSource: { type: "binding", path: "product.name" },
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_title",
        componentId: "screen_title",
        label: "Selfie instructions",
        name: "screenTitle",
        variant: "title",
        enabled: true,
        visible: true,
        span: 12,
      },
    ],
    body: [
      {
        __component: "ui.text",
        testId: "hint_1",
        componentId: "hint_1",
        label: "Ensure you are in a well-lit area",
        name: "hint1",
        variant: "body",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "hint_2",
        componentId: "hint_2",
        label: "Remove glasses before taking your selfie",
        name: "hint2",
        variant: "body",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "hint_3",
        componentId: "hint_3",
        label: "Remove hats or head coverings",
        name: "hint3",
        variant: "body",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "hint_4",
        componentId: "hint_4",
        label: "Keep a neutral expression and look directly at the camera",
        name: "hint4",
        variant: "body",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "hint_5",
        componentId: "hint_5",
        label: "Ensure your face is fully within the circle frame",
        name: "hint5",
        variant: "body",
        enabled: true,
        visible: true,
        span: 12,
      },
    ],
    footer: [
      {
        __component: "ui.button",
        testId: "start_button",
        componentId: "start_button",
        label: "Get started",
        name: "startButton",
        variant: "primary",
        enabled: true,
        visible: true,
        action: { type: "NEXT_SCREEN" },
        span: 12,
      },
    ],
  },

  {
    screenId: "ekyc_selfie",
    screenKey: "EKYC_SELFIE",
    version: 1,
    meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
    body: [
      {
        __component: "ui.camera-capture",
        testId: "selfie_camera",
        componentId: "selfie_camera",
        name: "selfieCamera",
        overlayShape: "circle",
        overlayHint: "Turn face left, then right, then smile",
        binding: { path: "selfieImage", scope: "journeyState" },
        onComplete: {
          action: {
            key: "ekycComplete",
            type: "api_call",
            payload: { serviceCode: "EKYC_LIVENESS", actionId: "ekyc-complete" },
          },
        },
        span: 12,
      },
    ],
    footer: [],
  },

  {
    screenId: "consent_form",
    screenKey: "CONSENT_FORM",
    version: 1,
    meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
    header: [
      {
        __component: "ui.progress-bar",
        testId: "progress_bar",
        componentId: "progress_bar",
        name: "progressBar",
        currentStep: 9,
        maxStep: 11,
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "product_name",
        componentId: "product_name",
        label: "",
        name: "productName",
        variant: "subtitle",
        enabled: true,
        visible: true,
        valueSource: { type: "binding", path: "product.name" },
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_title",
        componentId: "screen_title",
        label: "Statement of Consent",
        name: "screenTitle",
        variant: "title",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_subtitle",
        componentId: "screen_subtitle",
        label: "By continuing, you are providing all information and documents.",
        name: "screenSubtitle",
        variant: "subtitle",
        enabled: true,
        visible: true,
        span: 12,
      },
    ],
    body: [
      {
        __component: "ui.item-list",
        testId: "tnc_list",
        componentId: "tnc_list",
        key: "tncList",
        label: "Terms & Conditions",
        options: [
          {
            key: "tnc-bpat",
            label: "BPAT Personal Product and Feature Terms & Conditions",
            onTap: { key: "open_tnc_bpat", type: "open_document", payload: { document: "tnc_bpat" } },
          },
          {
            key: "tnc-savings",
            label: "Terms & Conditions Savings Account",
            onTap: { key: "open_tnc_savings", type: "open_document", payload: { document: "tnc_savings" } },
          },
          {
            key: "tnc-global",
            label: "Terms & Conditions Global Access",
            onTap: { key: "open_tnc_global", type: "open_document", payload: { document: "tnc_global" } },
          },
          {
            key: "tnc-mae",
            label: "Terms & Conditions MAE",
            onTap: { key: "open_tnc_mae", type: "open_document", payload: { document: "tnc_mae" } },
          },
        ],
        span: 12,
      },
      {
        __component: "ui.rich-text",
        testId: "data_verification_statement",
        componentId: "data_verification_statement",
        name: "dataVerificationStatement",
        content: [
          {
            type: "paragraph",
            children: [
              {
                type: "text",
                text: "I hereby declare that the information I have provided is accurate and complete, and I consent to Maybank processing my data in accordance with the Privacy Policy.",
              },
            ],
          },
        ],
        span: 12,
      },
      {
        __component: "ui.rich-text",
        testId: "offers_statement",
        componentId: "offers_statement",
        name: "offersStatement",
        content: [
          {
            type: "paragraph",
            children: [
              {
                type: "text",
                text: "By ticking the box below, I declare that I agree to receive information on other Maybank products and services.",
              },
            ],
          },
        ],
        span: 12,
      },
      {
        __component: "ui.checkbox",
        testId: "terms_accepted",
        componentId: "terms_accepted",
        title: "I agree & consent",
        label:
          "I have read, understood, and agree to the Terms & Conditions and consent to Maybank processing my personal data.",
        name: "termsAccepted",
        defaultValue: false,
        required: true,
        enabled: true,
        editable: true,
        visible: true,
        binding: { path: "termsAccepted", scope: "journeyState" },
        validations: [{ rule: "required", message: "You must agree to the terms to continue" }],
        span: 12,
      },
    ],
    footer: [
      {
        __component: "ui.button",
        testId: "next_button",
        componentId: "next_button",
        label: "Next",
        name: "nextButton",
        variant: "primary",
        enabled: true,
        visible: true,
        action: { type: "NEXT_SCREEN" },
        span: 12,
      },
    ],
  },

  {
    screenId: "confirmation",
    screenKey: "CONFIRMATION",
    version: 1,
    meta: { label: "Apply", enableBackButton: true, enableCloseButton: true },
    header: [
      {
        __component: "ui.progress-bar",
        testId: "progress_bar",
        componentId: "progress_bar",
        name: "progressBar",
        currentStep: 10,
        maxStep: 11,
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_subtitle",
        componentId: "screen_subtitle",
        label: "Apply for",
        name: "screenSubtitle",
        variant: "subtitle",
        enabled: true,
        visible: true,
        span: 12,
      },
      {
        __component: "ui.text",
        testId: "screen_title",
        componentId: "screen_title",
        label: "Global Access Account — Savings Account",
        name: "screenTitle",
        variant: "title",
        enabled: true,
        visible: true,
        span: 12,
      },
    ],
    body: [
      {
        __component: "ui.review-card",
        testId: "account_info_card",
        componentId: "account_info_card",
        name: "accountInfoCard",
        label: "Account info",
        enabled: true,
        visible: true,
        options: [
          { id: "mobileNumber", label: "Mobile number", path: "mobileNumber" },
          { id: "emailAddress", label: "Email address", path: "emailAddress" },
        ],
        span: 12,
      },
      {
        __component: "ui.review-card",
        testId: "ektp_details_card",
        componentId: "ektp_details_card",
        name: "ektpDetailsCard",
        label: "e-KTP details",
        enabled: true,
        visible: true,
        options: [
          { id: "ektpNumber", label: "e-KTP number", path: "ektpNumber" },
          { id: "fullName", label: "Full name", path: "fullName" },
          { id: "dateOfBirth", label: "Date of birth", path: "dateOfBirth" },
          { id: "placeOfBirth", label: "Place of birth", path: "placeOfBirth" },
          { id: "gender", label: "Gender", path: "gender" },
          { id: "religion", label: "Religion", path: "religion" },
          { id: "maritalStatus", label: "Marital status", path: "maritalStatus" },
          { id: "occupation", label: "Occupation", path: "occupation" },
          { id: "address", label: "Address", path: "address" },
          { id: "province", label: "Province", path: "province" },
          { id: "rtRw", label: "RT / RW", path: "rt" },
          { id: "postcode", label: "Postcode", path: "postcode" },
        ],
        span: 12,
      },
      {
        __component: "ui.review-card",
        testId: "npwp_details_card",
        componentId: "npwp_details_card",
        name: "npwpDetailsCard",
        label: "NPWP details",
        enabled: true,
        visible: true,
        options: [{ id: "npwpNumber", label: "NPWP number", path: "npwpNumber" }],
        span: 12,
      },
      {
        __component: "ui.review-card",
        testId: "employment_details_card",
        componentId: "employment_details_card",
        name: "employmentDetailsCard",
        label: "Employment details",
        enabled: true,
        visible: true,
        options: [
          { id: "employmentOccupation", label: "Occupation", path: "employmentOccupation" },
          { id: "employmentIndustry", label: "Industry", path: "employmentIndustry" },
          { id: "employmentCompanyName", label: "Company", path: "employmentCompanyName" },
          { id: "employmentJobTitle", label: "Job title", path: "employmentJobTitle" },
          { id: "employmentStatus", label: "Status", path: "employmentStatus" },
          { id: "employmentJoinDate", label: "Join date", path: "employmentJoinDate" },
          { id: "employmentOfficeAddress", label: "Office address", path: "employmentOfficeAddress" },
        ],
        span: 12,
      },
      {
        __component: "ui.review-card",
        testId: "financial_details_card",
        componentId: "financial_details_card",
        name: "financialDetailsCard",
        label: "Financial details",
        enabled: true,
        visible: true,
        options: [
          { id: "sourceOfIncome", label: "Source of income", path: "sourceOfIncome" },
          { id: "numberOfDependents", label: "Dependents", path: "numberOfDependents" },
          { id: "monthlyIncome", label: "Monthly income", path: "monthlyIncome" },
          { id: "purposeOfFunds", label: "Purpose of funds", path: "purposeOfFunds" },
          { id: "monthlyTransactionAmount", label: "Transaction amount", path: "monthlyTransactionAmount" },
          {
            id: "monthlyTransactionFrequency",
            label: "Transaction frequency",
            path: "monthlyTransactionFrequency",
          },
        ],
        span: 12,
      },
      {
        __component: "ui.review-card",
        testId: "residential_details_card",
        componentId: "residential_details_card",
        name: "residentialDetailsCard",
        label: "Residential details",
        enabled: true,
        visible: true,
        options: [
          { id: "residentialAddress", label: "Residential address", path: "residentialAddress" },
          { id: "residentialOwnershipStatus", label: "Ownership status", path: "residentialOwnershipStatus" },
          { id: "correspondenceAddress", label: "Correspondence address", path: "correspondenceAddress" },
        ],
        span: 12,
      },
    ],
    footer: [
      {
        __component: "ui.slide-to-confirm",
        testId: "slide_confirm",
        componentId: "slide_confirm",
        label: "Slide to confirm",
        name: "slideConfirm",
        action: {
          key: "submitApplication",
          type: "submit_journey",
          payload: { serviceCode: "CA_SUBMIT" },
        },
        span: 12,
      },
    ],
  },

  {
    screenId: "success",
    screenKey: "SUCCESS",
    version: 1,
    meta: { label: "Apply", enableBackButton: false, enableCloseButton: false },
    body: [
      {
        __component: "ui.banner",
        testId: "success_banner",
        componentId: "success_banner",
        label: "Your Global Access Account application has been submitted successfully.",
        name: "successBanner",
        variant: "success",
        span: 12,
      },
    ],
    footer: [],
  },

  {
    screenId: "ineligible",
    screenKey: "INELIGIBLE",
    version: 1,
    meta: { label: "Apply", enableBackButton: false, enableCloseButton: true },
    body: [
      {
        __component: "ui.banner",
        testId: "ineligible_banner",
        componentId: "ineligible_banner",
        label:
          "Unfortunately you do not meet the criteria for this product. Please contact our support team for more information.",
        name: "ineligibleBanner",
        variant: "error",
        span: 12,
      },
    ],
    footer: [
      {
        __component: "ui.button",
        testId: "back_home_button",
        componentId: "back_home_button",
        label: "Back to home",
        name: "backHomeButton",
        variant: "primary",
        enabled: true,
        visible: true,
        action: { type: "FINISH_JOURNEY" },
        span: 12,
      },
    ],
  },

  {
    screenId: "submit_failed",
    screenKey: "SUBMIT_FAILED",
    version: 1,
    meta: { label: "Apply", enableBackButton: false, enableCloseButton: true },
    body: [
      {
        __component: "ui.banner",
        testId: "failed_banner",
        componentId: "failed_banner",
        label: "We couldn't submit your application. If the problem persists, please contact support.",
        name: "failedBanner",
        variant: "warning",
        span: 12,
      },
    ],
    footer: [
      {
        __component: "ui.button",
        testId: "retry_button",
        componentId: "retry_button",
        label: "Try again",
        name: "retryButton",
        variant: "primary",
        enabled: true,
        visible: true,
        action: { type: "PREV_SCREEN" },
        span: 12,
      },
      {
        __component: "ui.button",
        testId: "back_home_button",
        componentId: "back_home_button",
        label: "Back to home",
        name: "backHomeButton",
        variant: "secondary",
        enabled: true,
        visible: true,
        action: { type: "FINISH_JOURNEY" },
        span: 12,
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Seed entry point
// ---------------------------------------------------------------------------

export async function seedApplyCaV2(strapi: StrapiInstance) {
  console.log("[seed-v2] Starting apply-ca-v2 seed…");

  for (const screenData of screens) {
    await createAndPublishScreen(strapi, screenData);
  }

  console.log("[seed-v2] Done.");
}
